### ISSUE TITLE
RTNETLINK answers: No such file or directory, "Failed to find specified qdisc"

### ISSUE THREAD

**Issue by btripathi123** [jeez/iproute2#4]
**Problem**: When I run tc tool with "etf" it give Error: RTNETLINK answers: No such file or directory

I am quiet sure it is because some driver is missing in my Linux kernel: .config File.

Could you please let me know which Driver modules are explicitly required for ETF.

**Command:** 
DSx86_32:/exchange/local# ./tc qdisc replace dev eth1 parent 100:1 etf clockid CLOCK_TAI delta 300000 offload
RTNETLINK answers: No such file or directory
DSx86_32:/exchange/local#

**STRACE Output:**

recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=120, type=NLMSG_ERROR, flags=NLM_F_ACK_TLVS, seq=1556017543, pid=2034}, {error=-ENOENT, msg={{len=64, type=0x24 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x500, seq=1556017543, pid=0}, "\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x00\x00\x00\x00\x08\x00\x01\x00\x6 5\x74\x66\x00\x14\x00\x02\x00"...}, {{nla_len=35, nla_type=NLMSGERR_ATTR_MSG}, **"Failed to find specified qdisc**"}}}, iov_len=32768}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 120
write(2, "RTNETLINK answers: No such file "..., 45**RTNETLINK answers: No such file or directory**
) = 45

Similar Problem I faced in past when used Tc tool with "mqprio" and "taprio" but it was solved when I included driver for respective feature.

for ex: Taprio works after including drivers at Networking support --> Networking options --> QOS and /or fair queueing

And 

mqprio work after including all driver at Networking support --> Networking options --> Netfilter --> core netfilter configuration 

you are requested to give your view.

Thanks & Regards
Bhaskar

**Comment by btripathi123** [comment]
mqprio command was having problem , now its solved

**Comment by Rakesh232323** [comment]
Hi,
I am planning to test taprio qdisc with the Intel210 NIC card,
Could you provide the link from where i can buy the right I210 NIC card which can support Taprio and CBS qdisc in Linux or windows.

**Comment by EnfangCui** [comment]
Hi,
I used the ubuntu 18.04 with Linux kernel 5.0.1 including "taprio" drivers at Networking support --> Networking options --> QOS and /or fair queueing. But when I run the "tc qdisc replace dev eth0 parent root handle 100 taprio " command, it gives error: "Unknown qdisc "taprio", hence option is unparsable". I wonder how to make the Linux support taprio. Can you give me a more detailed kernel configuration? Look forward to your kind reply. Thanks!

**Comment by kcn21** [comment]
Hi @btripathi123 @EnfangCui ,
Please share where to find  Networking support --> Networking options --> QOS and /or fair queueing.

@EnfangCui  I am also getting error: "Unknown qdisc "taprio", hence num_tc option is unparsable" when I run following taprio command:

sudo tc qdisc replace dev eth0 parent root handle 100 taprio num_tc 3  map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 queues 1@0 1@0 1@0  base-time 1000000000  sched-entry S 01 300000  sched-entry S 03 300000 sched-entry S 04 400000   flags 0x1 txtime-delay 500000  clockid CLOCK_TAI

Please tell how to solve the error.

Thanks, 
Kunj

**Comment by liing0228** [comment]
> Hi @btripathi123 @EnfangCui , Please share where to find Networking support --> Networking options --> QOS and /or fair queueing.
> 
> @EnfangCui I am also getting error: "Unknown qdisc "taprio", hence num_tc option is unparsable" when I run following taprio command:
> 
> sudo tc qdisc replace dev eth0 parent root handle 100 taprio num_tc 3 map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 queues 1@0 1@0 1@0 base-time 1000000000 sched-entry S 01 300000 sched-entry S 03 300000 sched-entry S 04 400000 flags 0x1 txtime-delay 500000 clockid CLOCK_TAI
> 
> Please tell how to solve the error.
> 
> Thanks, Kunj

hi @kcn21  did you fix the issue?
i faced the same problem

**Comment by kcn21** [comment]
> > Hi @btripathi123 @EnfangCui , Please share where to find Networking support --> Networking options --> QOS and /or fair queueing.
> > @EnfangCui I am also getting error: "Unknown qdisc "taprio", hence num_tc option is unparsable" when I run following taprio command:
> > sudo tc qdisc replace dev eth0 parent root handle 100 taprio num_tc 3 map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 queues 1@0 1@0 1@0 base-time 1000000000 sched-entry S 01 300000 sched-entry S 03 300000 sched-entry S 04 400000 flags 0x1 txtime-delay 500000 clockid CLOCK_TAI
> > Please tell how to solve the error.
> > Thanks, Kunj
> 
> hi @kcn21 did you fix the issue? i faced the same problem

Yes, you have to update the iproute2 package. You can use the following link.
https://github.com/shemminger/iproute2
